#!/bin/sh

if [ -z "$TMUX" ] && [ -z "$ZELLIJ" ]; then
    LOGO=$(find ~/.config/fastfetch/images/ | shuf -n1)
fi

if [ -n "$LOGO" ]; then
    echo "$LOGO"
    exit
fi

echo "$HOME/.config/fastfetch/logo"
