. cycle-values video-aspect "16:9" "4:3" "2.35:1" "-1" # Cycle through aspect ratio

ENTER    cycle-values fullscreen yes no   # Toggle full-screen
KP_ENTER cycle-values fullscreen yes no   # Toggle full-screen

MOUSE_BTN1 cycle-values fullscreen yes no # Right mouse button unbound
MOUSE_BTN0 cycle pause                    # Left mouse button to pause/resume

UP   add volume 2    # Volume increase by 2
DOWN add volume -2   # Volume decrease by 2

< add sub-delay -0.1 # Shift subtitles 100 ms earlier
> add sub-delay +0.1 # Delay subtitles by 100 ms

* set speed 1        # Increase the playback speed
+ add speed +0.1     # Increase the playback speed
- add speed -0.1     # Decrease the playback speed


