[config]

[templates.hyprland]
input_path = '~/.config/matugen/hyprland.matugen'
output_path = '~/.config/hypr/configs/colors.conf'
post_hook = 'hyprctl reload'

[templates.waybar]
input_path = '~/.config/matugen/colors.matugen'
output_path = '~/.config/waybar/colors.css'

[templates.wlogout]
input_path = '~/.config/matugen/colors.matugen'
output_path = '~/.config/wlogout/colors.css'
