[config]

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland.conf'
output_path = '~/.cache/matugen/hyprland.conf'

[templates.hyprpaper]
input_path = '~/.config/matugen/templates/hyprpaper.conf'
output_path = '~/.cache/matugen/hyprpaper.conf'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty.conf'
output_path = '~/.cache/matugen/kitty.conf'

[templates.alacritty]
input_path = '~/.config/matugen/templates/alacritty.toml'
output_path = '~/.cache/matugen/alacritty.toml'

[templates.ghostty]
input_path = '~/.config/matugen/templates/ghostty.ini'
output_path = '~/.cache/matugen/ghostty'

[templates.gtk-colors]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.cache/matugen/gtk-colors.css'

[templates.gtk]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.cache/matugen/gtk.css'

[templates.scss]
input_path = '~/.config/matugen/templates/colors.scss'
output_path = '~/.cache/matugen/colors.scss'

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi.rasi'
output_path = '~/.config/rofi/config.rasi'

[templates.discord]
input_path = '~/.config/matugen/templates/discord.css'
output_path = '~/.cache/matugen/discord.css'

[templates.spicetify]
input_path = '~/.config/matugen/templates/spicetify.ini'
output_path = '~/.cache/matugen/spicetify.ini'

[templates.pywalfox]
input_path = '~/.config/matugen/templates/pywalfox.json'
output_path = '~/.cache/wal/colors.json'
