[config]

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland.conf'
output_path = '~/.cache/matugen/hyprland.conf'
post_hook = 'hyprctl reload'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty.conf'
output_path = '~/.cache/matugen/kitty.conf'
post_hook = 'killall -SIGUSR1 kitty'

[templates.gtk]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.cache/matugen/gtk-colors.css'
post_hook = 'killall -SIGUSR2 waybar;swaync-client --reload-css'

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi.rasi'
output_path = '~/.config/rofi/config.rasi'

[templates.discord]
input_path = '~/.config/matugen/templates/discord.css'
output_path = '~/.cache/matugen/discord.css'

[templates.spicetify]
input_path = '~/.config/matugen/templates/spicetify.ini'
output_path = '~/.cache/matugen/spicetify.ini'
post_hook = 'sh ~/.config/hypr/scripts/spicetify.sh'

[templates.pywalfox]
input_path = '~/.config/matugen/templates/pywalfox.json'
output_path = '~/.cache/wal/colors.json'
post_hook = 'pywalfox update'
