[config]

[templates.hyprland]
input_path = '~/.config/matugen/hyprland.matugen'
output_path = '~/.config/hypr/configs/colors.conf'
post_hook = 'hyprctl reload'

[templates.waybar]
input_path = '~/.config/matugen/colors.matugen'
output_path = '~/.config/waybar/colors.css'

[templates.wlogout]
input_path = '~/.config/matugen/colors.matugen'
output_path = '~/.config/wlogout/colors.css'

[templates.gtk3]
input_path = '~/.config/matugen/gtk.matugen'
output_path = '~/.config/gtk-3.0/colors.css'

[templates.gtk4]
input_path = '~/.config/matugen/gtk.matugen'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.qt5ct]
input_path = '~/.config/matugen/qt.matugen'
output_path = '~/.config/qt5ct/colors/matugen.conf'

[templates.qt6ct]
input_path = '~/.config/matugen/qt.matugen'
output_path = '~/.config/qt6ct/colors/matugen.conf'
