variant: expressive
version: 2021
light: false

links:
    hyprland.conf: ~/.config/hypr/colors.conf
    colors.lua: ~/.config/wezterm/colors.lua
    spicetify-sleek.ini: ~/.config/spicetify/Themes/Sleek/color.ini
    kitty.conf: ~/.config/kitty/colors.conf
    pywalfox.json: ~/.cache/wal/colors.json
    rofi.rasi: ~/.config/rofi/config.rasi
    ghostty: ~/.config/ghostty/colors
    dunstrc: ~/.config/dunst/dunstrc

    colors.scss:
        - ~/.config/eww/colors.scss
        - ~/.config/waybar/colors.scss
        - ~/.config/swaync/colors.scss
        - ~/.config/wofi/colors.scss
        - ~/.config/swayosd/colors.scss
        - ~/git/dotfiles/.config/eww/colors.scss
        - ~/git/dotfiles/.config/waybar/colors.scss
        - ~/git/dotfiles/.config/swaync/colors.scss
        - ~/git/dotfiles/.config/wofi/colors.scss
        - ~/git/dotfiles/.config/swayosd/colors.scss

    colors.css:
        - ~/.config/waybar/colors.css

    qtct.colors:
        - ~/.config/qt5ct/colors/rong.colors
        - ~/.config/qt6ct/colors/rong.colors

    gtk.css:
        - ~/.config/gtk-3.0/gtk.css
        - ~/.config/gtk-4.0/gtk.css

    gtk-css.css:
        - ~/.config/wlogout/colors.css

    midnight-discord.css:
        - ~/.config/equibop/settings/quickCss.css
        - ~/.config/vesktop/settings/quickCss.css
