
[link]
"hyprland.conf" = "~/.config/hypr/colors.conf"
"colors.lua" = "~/.config/wezterm/colors.lua"
"colors.scss" = "~/.config/eww/styles/colors.scss"
"spicetify-sleek.ini" = "~/.config/spicetify/Themes/Sleek/color.ini"
"kitty.conf" = "~/.config/kitty/colors.conf"
"pywalfox.json" = "~/.cache/wal/colors.json"
"gtk.css" = [
    "~/.config/gtk-3.0/gtk.css",
    "~/.config/gtk-4.0/gtk.css",
]
"gtk-css.css" = [
    "~/.config/waybar/colors.css",
    "~/.config/swaync/colors.css",
    "~/.config/wlogout/colors.css",
]
"midnight-discord.css" = [
    "~/.config/equibop/settings/quickCss.css",
    "~/.config/vesktop/settings/quickCss.css",
]
