[link]
"hyprland.conf" = "~/.config/hypr/colors.conf"
"colors.lua" = "~/.config/wezterm/colors.lua"
"spicetify-sleek.ini" = "~/.config/spicetify/Themes/Sleek/color.ini"
"kitty.conf" = "~/.config/kitty/colors.conf"
"pywalfox.json" = "~/.cache/wal/colors.json"
"rofi.rasi" = "~/.config/rofi/config.rasi"

"colors.scss" = [
    "~/.config/eww/colors.scss",
    "~/.config/waybar/colors.scss",
    "~/.config/swaync/colors.scss",
    "~/.config/wofi/colors.scss",
]

"qtct.conf" = [
    "~/.config/qt5ct/colors/rong.conf",
    "~/.config/qt6ct/colors/rong.conf",
]

"gtk.css" = [
    "~/.config/gtk-3.0/gtk.css",
    "~/.config/gtk-4.0/gtk.css",
]

"gtk-css.css" = [
    "~/.config/wlogout/colors.css",
]

"midnight-discord.css" = [
    "~/.config/equibop/settings/quickCss.css",
    "~/.config/vesktop/settings/quickCss.css",
]
