
[link]
"colors.lua" = "~/.config/wezterm/colors.lua"
"gtk-css.css" = [
    "~/.config/waybar/colors.css",
    "~/.config/swaync/colors.css",
    "~/.config/wlogout/colors.css",
]
"midnight-discord.css" = [
    "~/.config/equibop/settings/quickCss.css",
    "~/.config/vesktop/settings/quickCss.css",
]
