# ~/.config/starship.toml

"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """\
$os$hostname$shell\
$directory\
( [\\[](red bold)$git_branch$hg_branch([:](green)$git_state$git_status)[\\]](red bold))\
$sudo\
$character\
"""

continuation_prompt = '[  => ](green bold)'

# right_format = '$docker_context$all'

[character]
success_symbol = '[ 󰁔](green bold)'
error_symbol = '[ 󰁔](red bold)'
vimcmd_symbol = '[ ](blue bold)'
vimcmd_replace_one_symbol = '[ /](yellow bold)'
vimcmd_replace_symbol = '[ /](yellow bold)'
vimcmd_visual_symbol = '[ |](green bold)'

[os]
format = '$symbol'
disabled = false

[os.symbols]
Windows = '[ ](#00C6FF)'
Ubuntu = '[󰕈 ](#FF7800)'
Arch = '[󰣇 ](#00C6FF)'

[hostname]
format = '[\($hostname\)]($style) '
style = 'yellow'

[shell]
format = '$indicator'
fish_indicator = '[󰈺](green bold)'
powershell_indicator = '󰨊'
bash_indicator = ''
cmd_indicator = ''
zsh_indicator = '[Z](bold)'
nu_indicator = "[󰟆](green)"
unknown_indicator = '$'
disabled = false

[directory]
format = ' [$path]($style)[$read_only]($read_only_style)'
read_only_style = 'red'
style = 'cyan bold'
read_only = '  '
home_symbol = ' ~'
truncation_length = 2
truncate_to_repo = false
truncation_symbol = '…/'

[sudo]
format = '[$symbol]($style)'
style = 'bold yellow'
symbol = ' 󱐋'
disabled = true

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style)'
symbol = ''
style = 'red'

[hg_branch]
format = '[ $symbol$branch ]($style)'
symbol = ' '

[git_state]
format = '([$state\(($progress_current/$progress_total)\)]($style))'

[git_status]
format = "($conflicted$staged$modified$deleted$renamed$untracked$stashed)($ahead_behind)"

conflicted = "[ !$count! ](red bold)"
ahead = "[↑${count}](yellow bold)"
behind = "[↓${count}](yellow bold)"
diverged = "[↑${ahead_count}↓${behind_count}](yellow bold)"
untracked = "[!$count](cyan bold)"
stashed = "[~$count](bold blue bold)"
modified = "[+$count](yellow bold)"
staged = "[+$count](green bold)"
renamed = "[>$count](green bold)"
deleted = "[-$count](red bold)"


# Right prompt

[username]
format = ' [ $user]($style)'

[cmd_duration]
format = '   [$duration](bold yellow)'
min_time = 500

[git_metrics]
format = '( [󰊢 ](red)\(([+$added]($added_style))([-$deleted]($deleted_style))\))'
disabled = false

# [custom.git_tag]
# format = "([$symbol($output)]($style))"
# command = "git describe --tags --abbrev=0"
# when = "git rev-parse --is-inside-work-tree"
# symbol = "󰓼 "
# style = "bold red"

[package]
format = ' [$symbol$version]($style) '

[nodejs]
format = ' [$symbol($version)]($style)'
style = 'bold green'

[bun]
format = ' [$symbol($version)]($style)'
style = 'bold white'

[python]
format = ' [${symbol}${pyenv_prefix}(${version})( \($virtualenv\))]($style)'
symbol = '󰌠 '

[rust]
format = ' [$symbol($version )]($style)'
symbol = '󱘗 '

[lua]
format = ' [$symbol($version )]($style)'
symbol = '󰢱 '

[golang]
format = ' [$symbol($version )]($style)'
symbol = '󰟓 '

[c]
format = " [$symbol($version(-$name) )]($style)"
symbol = " "

[docker_context]
format = " [$symbol$context]($style) "
style = "blue bold"
symbol = " "
detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]
disabled = false

[container]
format = "[$symbol \\[$name\\]]($style) "
disabled = false
