monitor=eDP-1,disable

$terminal = kitty
$browser = brave
$chat = equibop --start-minimized
$music = spotify
$fileManager = dolphin
$menu = wofi --show drun

source = ~/.config/hypr/configs/envs.conf
source = ~/.config/hypr/configs/colors.conf
source = ~/.config/hypr/configs/styles.conf
source = ~/.config/hypr/configs/keybindings.conf
source = ~/.config/hypr/configs/windows-rules.conf
source = ~/.config/hypr/configs/inputs.conf
source = ~/.config/hypr/configs/misc.conf

exec = mkdir -p ~/.local/share/logs
exec-once = swaync 2>&1 | tee -a ~/.local/share/logs/swaync.log
exec-once = ~/.config/hypr/scripts/waybar.sh
exec-once = ~/.config/hypr/scripts/hyprpaper.sh --startup

exec-once = wl-paste --type text --watch cliphist store # Stores only text data
exec-once = wl-paste --type image --watch cliphist store # Stores only image data

# My default setup
exec-once = [workspace 1 silent] $terminal
exec-once = [workspace 2 silent] $browser
exec-once = [workspace 3 silent] sleep 100 && $music
exec-once = [workspace 3 silent] sleep 50 && $chat
