monitor=eDP-1,disable

source = ~/.config/hypr/configs/envs.conf
source = ~/.config/hypr/configs/styles.conf
source = ~/.config/hypr/configs/keybindings.conf
source = ~/.config/hypr/configs/windows-rules.conf
source = ~/.config/hypr/configs/mics.conf

# exec-once = $terminal
# exec-once = nm-applet &
# exec-once = waybar & hyprpaper & firefox

exec-once = swaync
exec-once = waybar
exec-once = hyprpaper
exec-once = ~/.config/hypr/scripts/random-wall.sh
