source = ~/.cache/matugen/hyprland.conf

$font = JetBrainsMono Nerd Font

# GENERAL
general {
    disable_loading_bar = true
    hide_cursor = true
}

# BACKGROUND
background {
    monitor =
    path = $image
    blur_passes = 2
    color = $background
}

# TIME
label {
    monitor =
    text = cmd[update:30000] echo "$(date +"%I:%H %p")"
    color = $text
    font_size = 75
    font_family = $font
    position = -30, 0
    halign = right
    valign = top
}

# DATE
label {
    monitor =
    text = cmd[update:43200000] echo "$(date +"%A, %d %B %Y")"
    color = $on_primary_container
    font_size = 20
    font_family = $font
    position = -30, -120
    halign = right
    valign = top
}

# USER AVATAR

image {
    monitor =
    path = ~/.face
    size = 100
    border_color = $primary

    position = 0, 75
    halign = center
    valign = center
}

# INPUT FIELD
input-field {
    monitor =
    size = 300, 60
    outline_thickness = 4
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = $on_primary
    inner_color = $secondary
    font_color = $on_primary
    fade_on_empty = false
    placeholder_text = <span foreground="$on_primary_hex"><i>󰌾 Logged in as </i><span foreground="$on_primary_hex">$USER</span></span>
    hide_input = false
    check_color = $primary
    fail_color = $error
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    capslock_color = $primary
    position = 0, -35
    halign = center
    valign = center
}
