dialect = "us"
timezone = "local"

auto_sync = false
update_check = false

search_mode = "skim"

filter_mode = "global"
workspaces = false

filter_mode_shell_up_key_binding = "global"
search_mode_shell_up_key_binding = "skim"

# style = "compact"
invert = true
inline_height = 20

show_preview = true

exit_mode = "return-original"

history_format = "{duration}\t{command}"

show_help = true
show_tabs = true

secrets_filter = true
enter_accept = true

keymap_mode = "auto"

[stats]
common_prefix = ["sudo"]

[sync]
records = false
