[general]
import = ["~/.config/alacritty/theme.toml", "~/.cache/matugen/alacritty.toml"]
live_config_reload = true

[window]
padding = { x = 4, y = 4 }

[scrolling]
history = 10000

[font]
size = 9.5
normal.family = "JetbrainsMono Nerd Font"

[selection]
save_to_clipboard = true

[terminal]
shell = "/bin/fish"
osc52 = "CopyPaste"

[keyboard]
bindings = [{ key = "v", mods = "Control", action = "Paste" }]
